# Introducing Libraries: NumPy

![libgif](https://media0.giphy.com/media/7E8lI6TkLrvvAcPXso/giphy.gif?cid=790b76115d360a95792e4333770609b8&rid=giphy.gif)

## Introduction

#### Our goals today are to be able to: <br/>

- Identify and import Python modules and packages (libraries)
- Identify differences between NumPy and base Python in usage and operation
- Create a new module of our own
- Investigate table data in Pandas
- Manipulate Pandas DataFrames

### Activation:

![excel2](img/excelpic2.jpg)

Most people have used Microsoft Excel or Google sheets. But what are the limitations of excel?

- [Take a minute to read this article](https://www.bbc.com/news/magazine-22223190)
- make a list of problems excel presents

How is using python different?

Python
- create documentation of processes as you code
- reduces chances for human error
- do "drag and drop"
- repeatable
- transparent

## 1. Importing Python packages 


In an earlier lesson, we wrote a function to calculate the mean of an list. That was **tedious**. To make our code efficient we could store that function in a *python module* and call it later when we need it. 

And thankfully, other people have _also_ wrote and optimized functions and wrapped them into **modules** and **packages** (also known as _libraries_ )


### Terminology

![mod2](img/modules2.png)

### Terminology

![packages3](img/packages3.png)

<img src="img/python_def.png" width=400>

### pip & the Python Package Index

<img src="img/pypi_packages.png" width=600>

### You're not limited to PyPI

Make your own modules
![pipmod](img/import_modules.png)

![pippack](img/package_redo.png)

### First library we will import is `Numpy`


![numpy](https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png)

[NumPy](https://www.numpy.org/) is the fundamental package for scientific computing with Python. 


To import a package type `import` followed by the name of the package as shown below.

In [1]:
import numpy # Look, ma! we're importing!

#### Alias libraries

Many packages have a canonical way to import them with an abbreviated alias.

In [2]:
import numpy as np # np = alias

#### Other standard aliases 

In [3]:
import scipy
import pandas as pd
import matplotlib as mpl
import statsmodels as sm

ModuleNotFoundError: No module named 'statsmodels'

### Import specific modules from a larger package

In [ ]:
# sometimes we will want to import a specific module from a package
import matplotlib.pyplot as plt
from matplotlib import pyplot as plt 

#### Helpful links: package documentation

Packages have associated documentation to explain how to use the different tools included in a package.

_Sample of libraries_
- [NumPy](https://docs.scipy.org/doc/numpy/)
- [SciPy](https://docs.scipy.org/doc/scipy/reference/)
- [Pandas](http://pandas.pydata.org/pandas-docs/stable/)
- [Matplotlib](https://matplotlib.org/contents.html)

## 2. NumPy versus base Python

Now that we know packages exist, why do we want to use them? Let us examine a comparison between base Python and Numpy.

Python has lists and normal python can do basic math. NumPy, however, has the helpful objects called **arrays**.

Numpy has a few advantages over base Python which we will look at.

In [4]:
l = [1,2,3]
x=numpy.array([1,2,3])
print(x)


y=np.array([4,5,6])
print(y)

[1 2 3]
[4 5 6]


#### New type of object

In [5]:
type(x)

numpy.ndarray

### Numpy makes math easy

Because of numpy we can now get the **mean** and other quick math of lists and arrays.

In [6]:
example = [4,3,25,40,62,20]
print(np.mean(example))

25.666666666666668


#### Different types of arrays

In [7]:
names_list=['Bob','John','Sally']
names_array=numpy.char.array(['Bob','John','Sally']) #use numpy.array for numbers and numpy.char.array for strings
print(names_list)
print(names_array)

['Bob', 'John', 'Sally']
['Bob' 'John' 'Sally']


#### Array math in action

In [8]:
# Make a list and an array of three numbers

#your code here
numbers_list = [5,22,33,90]
numbers_array = np.array([5,22,33,90])

In [9]:
# divide your array by 2

numbers_array/2

array([ 2.5, 11. , 16.5, 45. ])

In [10]:
# divide your list by 2

numbers_list/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

Numpy arrays support the `div()` operator while python lists do not. There are other things that make it useful to utilize numpy over base python for evaluating data.

In [11]:
# shape tells us the size of the array

numbers_array.shape

(4,)

### Numpy array and matrix creation functions

Take 5 minutes and explore each of the following functions.  What does each one do?  What is the syntax of each?
- `np.zeros()`
- `np.ones()`
- `np.full()`
- `np.eye()`
- `np.random.random()`

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.full((3,3),3.3)


array([[3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3],
       [3.3, 3.3, 3.3]])

In [15]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.random(6)

array([0.86763248, 0.1002723 , 0.60483022, 0.96156867, 0.65820647,
       0.86572416])

### Slicing in NumPy

In [17]:
# Selection and assignment work as you might expect
numbers_array[1]

22

In [18]:
numbers_array[1] = 10
numbers_array

array([ 5, 10, 33, 90])

In [ ]:
# We remember slicing from lists
numbers_list = list(range(10))
numbers_list[3:7]

In [ ]:
# Slicing in NumPy Arrays is very similar!
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

In [ ]:
a.shape

In [ ]:
# first 2 rows, columns 1 & 2 (remember 0-index!)
b = a[:2, 1:3]
b

### Datatypes in NumPy

In [ ]:
a.dtype

In [ ]:
names_list.dtype

In [ ]:
a.astype(np.float64)

### More Array Math 
#### Adding matrices 

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)

In [ ]:
print(np.add(x, y))

#### Subtracting matrices 

In [ ]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)

In [ ]:
print(np.subtract(x, y))

#### Multiplying matrices 

In [19]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)

[ 4 10 18]


In [20]:
print(np.multiply(x, y))

[ 4 10 18]


#### Dividing matrices 

In [21]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)

[0.25 0.4  0.5 ]


In [22]:
print(np.divide(x, y))

[0.25 0.4  0.5 ]


#### Raising matrices to powers 

In [23]:
# Elementwise square root; both produce the same array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(x ** (1/2))

[1.         1.41421356 1.73205081]


In [24]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081]


### Numpy is faster

Below, you will find a piece of code we will use to compare the speed of operations on a list and operations on an array. In this speed test, we will use the package [time](https://docs.python.org/3/library/time.html).

In [25]:
import time
import numpy as np

size_of_vec = 1000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X))]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print("python: " + str(t1), "numpy: "+ str(t2))
print("Numpy is in this example " + str(t1/t2) + " times faster!")

python: 0.0002639293670654297 numpy: 2.8848648071289062e-05
Numpy is in this example 9.148760330578513 times faster!


In pairs, run the speed test with a different number, and share your results with the class.

## 3. Making our own module
<img src="https://media1.giphy.com/media/dW0KhIROCaAdCO0V3S/giphy.gif?cid=790b76115d36096678416c65519d8082&rid=giphy.gif" width=300>

In [ ]:
# this option will re-import your module each time you save an update to it

%load_ext autoreload
%autoreload 2

In [ ]:
import temperizer as tp

## Example: Convert F to C

1. This function is already implemented in `temperizer.py`.
2. Notice that we can call the imported function and see the result.

In [ ]:
# 32F should equal 0C
tps.convert_f_to_c(32)

In [ ]:
# -40F should equal -40C
tps.convert_f_to_c(-40)

In [ ]:
# 212F should equal 100C
tps.convert_f_to_c(212)

## Your turn: Convert C to F

1. Find the stub function in `temperizer.py`
2. The word `pass` means "this space intentionally left blank."
3. Add your code _in place of_ the `pass` keyword, _below_ the docstring.
4. Run these cells and make sure that your code works.

In [ ]:
# 0C should equal 32F
tps.convert_c_to_f(0)

In [ ]:
# -40C should equal -40F
tps.convert_c_to_f(-40)

In [ ]:
# 100C should equal 212F
tps.convert_c_to_f(100)

## Next: Adding New Functions

You need to add support for Kelvin to the `temperizer` library.

1. Create new _stub functions_ in `temperizer.py`:

    * `convert_c_to_k`
    * `convert_f_to_k`
    * `convert_k_to_c`
    * `convert_k_to_f`

    Start each function with a docstring and the `pass` keyword, e.g.:

    ```
    def convert_f_to_k(temperature_f):
        """Convert Fahrenheit to Kelvin."""
        pass
    ```

2. Add cells to this notebook to test and validate these functions, similar to the ones above.

3. Then, go back to `temperizer.py` to replace `pass` with your code.

4. Run the notebook cells to make sure that your new functions work.

#### Small note:

Docstrings (those lines with `""" """` on either side) allow us to create self-documented code. 

Now later, if you forget what each function does, you can use the `?` or `help` functions the same way you would with other functions, and your documentation will show up!

In [ ]:
tps.convert_f_to_c()

### Extra credit:

make a function in your temperizer that will take a temp in F, and print out:

```
The temperature [number] F is:
    - x in C
    - y in k
```

In [ ]:
tps.convert_f_to_all(89)

## Enter: Pandas

<img src="https://cdn-images-1.medium.com/max/1600/1*9IU5fBzJisilYjRAi-f55Q.png" width=600>  




- The data manipulation capabilities of Pandas are built on top of the numpy library.
- Pandas dataframe object represents a spreadsheet with cell values, column names, and row index labels.

### 1. Importing and reading data with Pandas!

#### Let's use pandas to read some csv files so we can interact with them.



In [26]:
# First, let's check which directory we are in so the files we expect to see are there.
!pwd
!ls -la

/Users/michael/Documents/flatiron/dc-ds-021720/mod-1/day-3-numpy-pandas
total 304
drwxr-xr-x   9 michael  staff    288 Mar  3 11:55 .
drwxr-xr-x  17 michael  staff    544 Mar  3 11:55 ..
-rw-r--r--@  1 michael  staff   6148 Feb 25 11:10 .DS_Store
drwxr-xr-x   5 michael  staff    160 Feb 25 10:38 .ipynb_checkpoints
drwxr-xr-x   4 michael  staff    128 Feb 20 11:36 data
drwxr-xr-x  12 michael  staff    384 Feb 20 11:36 img
-rwxr-xr-x   1 michael  staff  58180 Mar  3 11:55 libraries_numpy_pandas.ipynb
-rwxr-xr-x   1 michael  staff  81676 Feb 25 10:37 libraries_numpy_pandas_enkeboll.ipynb
-rwxr-xr-x   1 michael  staff    953 Feb 20 11:36 temperizer.py


In [27]:
import pandas as pd

example_csv = pd.read_csv('data/example1.csv')

There is also `read_excel`, `read_html`, and many other pandas `read_` functions.  
http://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

In [28]:
example_csv.describe()

Title1 Title2    Title3
count          2      2         2
unique         2      2         2
top     example1    two  example3
freq           1      1         1

Try loading in the example file in the `data` directory called `made_up_jobs.csv` using pandas.

In [29]:
# read in your csv here!
muj = pd.read_csv('data/made_up_jobs.csv')

# remember that it's nice to be able to look at your data, so let's do that here, too.
muj.head()

ID           Name                       Job  Years Employed
0   0   Bob Bobberty  Underwater Basket Weaver              13
1   1   Susan Smells             Salad Spinner               5
2   2  Alex Lastname      Productivity Manager               2
3   3        Rudy P.                Being cool              55
4   4        Rudy G.  Being compared to Rudy P              50

### 2. Utilizing and identifying Pandas objects

- What is a DataFrame object and what is a Series object? 
- How are they different from Python lists?

These are questions we will cover in this section. To start, let's start with this list of fruits.

In [30]:
fruits = ['Apple', 'Orange', 'Watermelon', 'Lemon', 'Mango']

print(fruits)

['Apple', 'Orange', 'Watermelon', 'Lemon', 'Mango']


Using our list of fruits, we can create a pandas object called a 'series' which is much like an array or a vector.

In [31]:
fruits_series = pd.Series(fruits)

print(fruits_series)
type(fruits_series)

0         Apple
1        Orange
2    Watermelon
3         Lemon
4         Mango
dtype: object


pandas.core.series.Series

One difference between python **list objects** and pandas **series objects** is the fact that you can define the index manually for a **series objects**.

In [32]:
ind = ['a', 'b', 'c', 'd', 'e']

fruits_series = pd.Series(fruits, index=ind)

print(fruits_series)

a         Apple
b        Orange
c    Watermelon
d         Lemon
e         Mango
dtype: object


With a partner, create your own custom series from a list of lists.

In [33]:
list_of_lists = [['cat'], ['dog'], ['horse'], ['cow'], ['macaw']]

# create custom indices for your series
ind = ['a', 'b', 'c', 'd', 'e']

elements=[x[0].lower() for x in list_of_lists]

# create the series using your list objects
# You can use either a for loop or also pd.Series
list_of_lists_series = pd.Series(elements, index=ind)

# print your series
print(list_of_lists_series)
type(list_of_lists_series)

a      cat
b      dog
c    horse
d      cow
e    macaw
dtype: object


pandas.core.series.Series

We can do a simliar thing with Python dictionaries. This time, however, we will create a DataFrame object from a python dictionary.

In [34]:
# Dictionary with list object in values
student_dict = {
    'name': ['Samantha', 'Alex', 'Dante'],
    'age': ['35', '17', '26'],
    'city': ['Houston', 'Seattle', 'New york']
}

students_df = pd.DataFrame(student_dict)

students_df.head()

name age      city
0  Samantha  35   Houston
1      Alex  17   Seattle
2     Dante  26  New york

In [35]:
#to find data types of columns
students_df.dtypes

name    object
age     object
city    object
dtype: object

Let's change the data type of ages to int.

In [36]:
# We can also change a columns type but the change has to make sense.
students_df.age = students_df.age.values

#Uncomment line below and observe what happens when trying to convert student's name to int or float
#students_df.name = students_df.name.astype(int)

#How about what happens converting numeric to string
students_df.age = students_df.age.astype(str)

students_df.dtypes

name    object
age     object
city    object
dtype: object

We can also use a custom index for these items. For example, we might want them to be the individual student ID numbers.

In [37]:
school_ids = ['1111', '1145', '0096']

# Notice here we use pd.DataFrame not pd.Series as we did for a pandas series.
students_df = pd.DataFrame(student_dict, index=school_ids)

students_df.head()

name age      city
1111  Samantha  35   Houston
1145      Alex  17   Seattle
0096     Dante  26  New york

Using Pandas, we can also rename column names.

In [38]:
students_df.columns = ['NAME', 'AGE', 'HOME']
students_df.head()

NAME AGE      HOME
1111  Samantha  35   Houston
1145      Alex  17   Seattle
0096     Dante  26  New york

Or, we can also change the column names using the rename function.

In [39]:
students_df.rename(columns={"AGE": "YEARS"})

NAME YEARS      HOME
1111  Samantha    35   Houston
1145      Alex    17   Seattle
0096     Dante    26  New york

In [40]:
# Notice what happens when we print students_df

students_df

NAME AGE      HOME
1111  Samantha  35   Houston
1145      Alex  17   Seattle
0096     Dante  26  New york

In [41]:
# If you want the file to save over itself, use the option `inplace = True`.
students_df.rename(columns={'AGE': 'YEARS'}, inplace=True)
students_df.head()

NAME YEARS      HOME
1111  Samantha    35   Houston
1145      Alex    17   Seattle
0096     Dante    26  New york

Similarly, there is a tool to remove rows and columns from your DataFrame

In [42]:
students_df.drop(columns=['YEARS', 'HOME'])

NAME
1111  Samantha
1145      Alex
0096     Dante

In [43]:
#Notice again what happens if we print students_df 
students_df

NAME YEARS      HOME
1111  Samantha    35   Houston
1145      Alex    17   Seattle
0096     Dante    26  New york

In [44]:
students_df.drop(columns=['YEARS', 'HOME'], inplace=True)
students_df

NAME
1111  Samantha
1145      Alex
0096     Dante

If you want the file to save over itself, use the option `inplace = True`.

Every function has options. Let's read more about `drop` [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)

### 3. Filtering Data Using Pandas
There are several ways to grab particular data from a DataFrame. 
- Python lists allow for selection of data only through integer location. 
- You can use a single integer or slice notation to make the selection but NOT a list of integers.
- Dictionaries only allow selection with a single label. Slices and lists of labels are not allowed.

In [45]:
l = [1, 2, 3, 4, 5]
l[[0, 5]]

TypeError: list indices must be integers or slices, not list

### DataFrames can be indexed by column name (label) or row name (index) or by position.   
#### The `.loc` method is used for indexing by name.  
#### While `.iloc` is used for indexing by number.

In [46]:
student_dict = {
    'name': ['Samantha', 'Alex', 'Dante'],
    'age': ['35', '17', '26'],
    'city': ['Houston', 'Seattle', 'New york']
}

students_df = pd.DataFrame(student_dict)

In [47]:
students_df.loc[:, 'name']

0    Samantha
1        Alex
2       Dante
Name: name, dtype: object

### Let's take a look at `.iloc`
#### `.iloc` takes slices based on index position.
#### `.iloc` stands for integer location so that should help with remember what it does
#### `.iloc`[row , column]

In [48]:
# returns the first row
students_df.iloc[0]

name    Samantha
age           35
city     Houston
Name: 0, dtype: object

In [49]:
# returns the first column
students_df.iloc[:, 0]

0    Samantha
1        Alex
2       Dante
Name: name, dtype: object

In [50]:
# returns first two rows notice that ILOC performs regular python slicing.
students_df.iloc[0:2]

name age     city
0  Samantha  35  Houston
1      Alex  17  Seattle

In [51]:
# returns the first two columns
students_df.iloc[:, 0:2]

name age
0  Samantha  35
1      Alex  17
2     Dante  26

In [52]:
# returns first row and columns 1 and 2
students_df.iloc[0:1, 0:2]

name age
0  Samantha  35

### How would we use `.iloc` to return the last item in the last row?


In [53]:
# return the last item in the last row using iloc

### How would we use `.iloc` to return the last item in the last column?


In [54]:
# return the last item in the last column using iloc

### What if we only want certain columns or rows?

In [55]:
# Don't do students_df.iloc[0, 2]
students_df.iloc[[0, 2]]

name age      city
0  Samantha  35   Houston
2     Dante  26  New york

In [56]:
students_df.iloc[[0, 2], [0, 2]]

name      city
0  Samantha   Houston
2     Dante  New york

### Let's take a look at `.loc`
#### Label based method. 
#### Names or labels of the index is used when taking slices.
#### Also supports boolean subsetting.

In [ ]:
# We will use loc to return rows and columns based on labels. Let's look at the students_df DataFrame again.
students_df

In [ ]:
# returns the student information associated with index 0
students_df.loc[0]

In [ ]:
# returns the student information for row index 0 to 2 inclusive.
# note iloc would return normal python slicing not including 2 as demonstrated above.
students_df.loc[0:2]

In [ ]:
# returns the column labeled 'age'
students_df.loc[:, 'age']

In [ ]:
# returns the column labeled 'age' and index values 1 to 2.
# gives us the values of the rows with index from 1 to 2 (inclusive)
# and columns labeled age"
students_df.loc[1:2, 'age']

In [ ]:
# returns the column labeled 'age' and index values 1 to 2.
# gives us the values of the rows with index from 1 to 2 (inclusive)
# and columns labeled age to city (inclusive)"
students_df.loc[1:2, 'age':'city']

In [ ]:
# What should we get?
students_df.loc[1:2, ['name', 'city']]

In [ ]:
# How about?
students_df.loc[[0, 2], ['name', 'city']]

In [ ]:
# if index rearranged
school_ids = ['5', '11', '3']
students_df = pd.DataFrame(student_dict, index=school_ids)

In [ ]:
students_df

In [ ]:
# What should we get now?
students_df.loc[[0, 2], ['name', 'city']]

In [ ]:
# What should we get now?
students_df.loc[['5', '11'], ['name', 'city']]

In [ ]:
students_df.set_index("name", inplace=True)
students_df

In [ ]:
students_df.loc[['Samantha']]

In [ ]:
# Subsetting nonconsecutive rows
students_df.loc[['Samantha', 'Dante']]

In [ ]:
# Samantha to the end
students_df.loc['Samantha':]

In [ ]:
# return the first and last rows using one loc command

### Boolean Subsetting

In [ ]:
student_dict = {
    'name': ['Samantha', 'Alex', 'Dante', 'Samantha'],
    'age': ['35', '17', '26', '21'],
    'city': ['Houston', 'Seattle', 'New york', 'Atlanta'],
    'state': ['Texas', 'Washington', 'New York', 'Georgia']
}

students_df = pd.DataFrame(student_dict)

In [ ]:
# The statement data[‘name’] == ‘Samantha’] produces a Pandas Series with a True/False value for every row
# in the ‘data’ DataFrame, where there are “True” values for the rows where the name is “Samantha”.
# These type of boolean arrays can be passed directly to the .loc indexer.
students_df.loc[students_df['name'] == 'Samantha']

In [ ]:
# What about if we only want the city and state of the selected students with the name Samantha?
students_df.loc[students_df['name'] == 'Samantha', ['city', 'state']]

In [ ]:
# What amount if we want to select a student of a specific age?
students_df.loc[students_df['age'] == '21']

In [ ]:
# What amount if we want to select a student of a specific age?
students_df.loc[(students_df['age'] == '21') &
                (students_df['city'] == 'Atlanta')]

In [58]:
# What should be returned?
students_df.loc[(students_df['age'] == '35') &
                (students_df['city'] == 'Atlanta')]

Empty DataFrame
Columns: [name, age, city]
Index: []

In [59]:
## Enter: Pandas

<img src="https://cdn-images-1.medium.com/max/1600/1*9IU5fBzJisilYjRAi-f55Q.png" width=600>  




- The data manipulation capabilities of Pandas are built on top of the numpy library.
- Pandas dataframe object represents a spreadsheet with cell values, column names, and row index labels.

### 1. Importing and reading data with Pandas!

#### Let's use pandas to read some csv files so we can interact with them.



# First, let's check which directory we are in so the files we expect to see are there.
!pwd
!ls -la

import pandas as pd

example_csv = pd.read_csv('data/example1.csv')

There is also `read_excel`, `read_html`, and many other pandas `read_` functions.  
http://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

example_csv.describe()

Try loading in the example file in the `data` directory called `made_up_jobs.csv` using pandas.

# read in your csv here!
muj = pd.read_csv('data/made_up_jobs.csv')

# remember that it's nice to be able to look at your data, so let's do that here, too.
muj.head()

### 2. Utilizing and identifying Pandas objects

- What is a DataFrame object and what is a Series object? 
- How are they different from Python lists?

These are questions we will cover in this section. To start, let's start with this list of fruits.

fruits = ['Apple', 'Orange', 'Watermelon', 'Lemon', 'Mango']

print(fruits)

Using our list of fruits, we can create a pandas object called a 'series' which is much like an array or a vector.

fruits_series = pd.Series(fruits)

print(fruits_series)
type(fruits_series)

One difference between python **list objects** and pandas **series objects** is the fact that you can define the index manually for a **series objects**.

ind = ['a', 'b', 'c', 'd', 'e']

fruits_series = pd.Series(fruits, index=ind)

print(fruits_series)

With a partner, create your own custom series from a list of lists.

list_of_lists = [['cat'], ['dog'], ['horse'], ['cow'], ['macaw']]

# create custom indices for your series
ind = ['a', 'b', 'c', 'd', 'e']

elements=[x[0].lower() for x in list_of_lists]

# create the series using your list objects
# You can use either a for loop or also pd.Series
list_of_lists_series = pd.Series(elements, index=ind)

# print your series
print(list_of_lists_series)
type(list_of_lists_series)

We can do a simliar thing with Python dictionaries. This time, however, we will create a DataFrame object from a python dictionary.

# Dictionary with list object in values
student_dict = {
    'name': ['Samantha', 'Alex', 'Dante'],
    'age': ['35', '17', '26'],
    'city': ['Houston', 'Seattle', 'New york']
}

students_df = pd.DataFrame(student_dict)

students_df.head()

#to find data types of columns
students_df.dtypes

Let's change the data type of ages to int.

# We can also change a columns type but the change has to make sense.
students_df.age = students_df.age.values

#Uncomment line below and observe what happens when trying to convert student's name to int or float
#students_df.name = students_df.name.astype(int)

#How about what happens converting numeric to string
students_df.age = students_df.age.astype(str)

students_df.dtypes

We can also use a custom index for these items. For example, we might want them to be the individual student ID numbers.

school_ids = ['1111', '1145', '0096']

# Notice here we use pd.DataFrame not pd.Series as we did for a pandas series.
students_df = pd.DataFrame(student_dict, index=school_ids)

students_df.head()

Using Pandas, we can also rename column names.

students_df.columns = ['NAME', 'AGE', 'HOME']
students_df.head()

Or, we can also change the column names using the rename function.

students_df.rename(columns={"AGE": "YEARS"})

# Notice what happens when we print students_df

students_df

# If you want the file to save over itself, use the option `inplace = True`.
students_df.rename(columns={'AGE': 'YEARS'}, inplace=True)
students_df.head()

Similarly, there is a tool to remove rows and columns from your DataFrame

students_df.drop(columns=['YEARS', 'HOME'])

#Notice again what happens if we print students_df 
students_df

students_df.drop(columns=['YEARS', 'HOME'], inplace=True)
students_df

If you want the file to save over itself, use the option `inplace = True`.

Every function has options. Let's read more about `drop` [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)

### 3. Filtering Data Using Pandas
There are several ways to grab particular data from a DataFrame. 
- Python lists allow for selection of data only through integer location. 
- You can use a single integer or slice notation to make the selection but NOT a list of integers.
- Dictionaries only allow selection with a single label. Slices and lists of labels are not allowed.

l = [1, 2, 3, 4, 5]
l[[0, 5]]

### DataFrames can be indexed by column name (label) or row name (index) or by position.   
#### The `.loc` method is used for indexing by name.  
#### While `.iloc` is used for indexing by number.

student_dict = {
    'name': ['Samantha', 'Alex', 'Dante'],
    'age': ['35', '17', '26'],
    'city': ['Houston', 'Seattle', 'New york']
}

students_df = pd.DataFrame(student_dict)

students_df.loc[:, 'name']

### Let's take a look at `.iloc`
#### `.iloc` takes slices based on index position.
#### `.iloc` stands for integer location so that should help with remember what it does
#### `.iloc`[row , column]

# returns the first row
students_df.iloc[0]

# returns the first column
students_df.iloc[:, 0]

# returns first two rows notice that ILOC performs regular python slicing.
students_df.iloc[0:2]

# returns the first two columns
students_df.iloc[:, 0:2]

# returns first row and columns 1 and 2
students_df.iloc[0:1, 0:2]

### How would we use `.iloc` to return the last item in the last row?


# return the last item in the last row using iloc

### How would we use `.iloc` to return the last item in the last column?


# return the last item in the last column using iloc

### What if we only want certain columns or rows?

# Don't do students_df.iloc[0, 2]
students_df.iloc[[0, 2]]

students_df.iloc[[0, 2], [0, 2]]

### Let's take a look at `.loc`
#### Label based method. 
#### Names or labels of the index is used when taking slices.
#### Also supports boolean subsetting.

# We will use loc to return rows and columns based on labels. Let's look at the students_df DataFrame again.
students_df

# returns the student information associated with index 0
students_df.loc[0]

# returns the student information for row index 0 to 2 inclusive.
# note iloc would return normal python slicing not including 2 as demonstrated above.
students_df.loc[0:2]

# returns the column labeled 'age'
students_df.loc[:, 'age']

# returns the column labeled 'age' and index values 1 to 2.
# gives us the values of the rows with index from 1 to 2 (inclusive)
# and columns labeled age"
students_df.loc[1:2, 'age']

# returns the column labeled 'age' and index values 1 to 2.
# gives us the values of the rows with index from 1 to 2 (inclusive)
# and columns labeled age to city (inclusive)"
students_df.loc[1:2, 'age':'city']

# What should we get?
students_df.loc[1:2, ['name', 'city']]

# How about?
students_df.loc[[0, 2], ['name', 'city']]

# if index rearranged
school_ids = ['5', '11', '3']
students_df = pd.DataFrame(student_dict, index=school_ids)

students_df

# What should we get now?
students_df.loc[[0, 2], ['name', 'city']]

# What should we get now?
students_df.loc[['5', '11'], ['name', 'city']]

students_df.set_index("name", inplace=True)
students_df

students_df.loc[['Samantha']]

# Subsetting nonconsecutive rows
students_df.loc[['Samantha', 'Dante']]

# Samantha to the end
students_df.loc['Samantha':]

# return the first and last rows using one loc command

### Boolean Subsetting

student_dict = {
    'name': ['Samantha', 'Alex', 'Dante', 'Samantha'],
    'age': ['35', '17', '26', '21'],
    'city': ['Houston', 'Seattle', 'New york', 'Atlanta'],
    'state': ['Texas', 'Washington', 'New York', 'Georgia']
}

students_df = pd.DataFrame(student_dict)

# The statement data[‘name’] == ‘Samantha’] produces a Pandas Series with a True/False value for every row
# in the ‘data’ DataFrame, where there are “True” values for the rows where the name is “Samantha”.
# These type of boolean arrays can be passed directly to the .loc indexer.
students_df.loc[students_df['name'] == 'Samantha']

# What about if we only want the city and state of the selected students with the name Samantha?
students_df.loc[students_df['name'] == 'Samantha', ['city', 'state']]

# What amount if we want to select a student of a specific age?
students_df.loc[students_df['age'] == '21']

# What amount if we want to select a student of a specific age?
students_df.loc[(students_df['age'] == '21') &
                (students_df['city'] == 'Atlanta')]

# What should be returned?
students_df.loc[(students_df['age'] == '35') &
                (students_df['city'] == 'Atlanta')]

SyntaxError: invalid syntax (<ipython-input-59-30246d520cbd>, line 3)

In [60]:
students_df.loc[0]

name    Samantha
age           35
city     Houston
Name: 0, dtype: object

In [61]:
students_df.loc[1:2, 'age']


1    17
2    26
Name: age, dtype: object

In [62]:
type(students_df.loc[1:2, 'age'])

pandas.core.series.Series

In [64]:
students_df.loc[students_df['name'] == 'Samantha']


name age     city
0  Samantha  35  Houston